@WeatherApi_HostAddress = http://localhost:5170
@Api_NgrokAddress = https://agonizing-enzyme-paddle.ngrok-free.dev

GET {{WeatherApi_HostAddress}}/weatherforecast?latitude=50.4&longitude=32
Accept: application/json

###

GET {{Api_NgrokAddress}}/weatherforecast?latitude=50.4&longitude=32
Accept: application/json

###

POST {{WeatherApi_HostAddress}}/cities/create?name=London&state=England&country=United Kingdom&countryCode=826&touristRating=5&dateEstablished=1965-01-01&estimatedPopulation=8900000
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/cities/36da18b9-71ab-4f30-ae39-ed48c03917bd/details
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/cities/search?name=london
Accept: application/json

###

PATCH {{WeatherApi_HostAddress}}/cities/B5130179-0F4F-428C-B1BC-37195F386300/update?touristRating=5
Accept: application/json

### 

DELETE {{WeatherApi_HostAddress}}/cities/B5130179-0F4F-428C-B1BC-37195F386300
Accept: application/json