@WeatherApi_HostAddress = http://localhost:5170
@Api_NgrokAddress = https://agonizing-enzyme-paddle.ngrok-free.dev

GET {{WeatherApi_HostAddress}}/weatherforecast?latitude=50.4&longitude=32
Accept: application/json

###

GET {{Api_NgrokAddress}}/weatherforecast?latitude=50.4&longitude=32
Accept: application/json

###

POST {{WeatherApi_HostAddress}}/cities/create
Content-Type: application/json

{
  "name": "London",
  "countryCode": "826"
}

###

GET {{WeatherApi_HostAddress}}/cities/3/details
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/cities/search?name=london&pageSize=4&page=0
Accept: application/json

###

PATCH {{WeatherApi_HostAddress}}/cities/3/update
Content-Type: application/json

{
    "touristRating": 4.6,
    "dateEstablished": "2026-11-17",
    "estimatedPopulation": 1243214326
}

### 

DELETE {{WeatherApi_HostAddress}}/cities/3
Accept: application/json

###

GET {{WeatherApi_HostAddress}}/cities/find?name=tok
Accept: application/json